name: pages build and deployment
on: push
jobs:
  check-status-action:
    runs-on: ubuntu-latest
    steps: 
      - name: test
        uses: paper-spa/check-deployment-status@main
        with:
          status_url: "www.google.com"
  checkout-and-deployment:
    runs-on: ubuntu-latest
    outputs:
      status_url: ${{steps.artifact_upload.outputs.status_url}}
      test: ${{steps.artifact_upload.outputs.test}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Build page with Jekyll
        uses: paper-spa/pages-jekyll@v4.0.0
      - name: archive build output
        run: tar --directory _site/ -c -v -f artifact.tar .
      - name: artifact_upload
        uses: paper-spa/upload-artifact@main
        with:
          name: artifact
          path: ${{ github.workspace }}/artifact.tar
          token: ${{ secrets.TOKEN_FOR_API }}
  check-deployment:
    runs-on: ubuntu-latest
    needs: checkout-and-deployment
    steps:
      - name: Check deployment status
        run: echo "${{needs.checkout-and-deployment.outputs.status_url}} + ${{needs.checkout-and-deployment.outputs.test}}"


