name: pages build and deployment
on: push
jobs:
  checkout-and-deployment:
    runs-on: ubuntu-latest
    outputs:
      status_url: ${{steps.artifact-upload.outputs.status_url}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Build page with Jekyll
        uses: paper-spa/pages-jekyll@v4.0.0
      - name: archive build output
        run: tar --directory _site/ -c -v -f artifact.tar .
      - name: artifact-upload
        uses: paper-spa/upload-artifact@output-url
        with:
          name: artifact
          path: ${{ github.workspace }}/artifact.tar
          token: ${{ secrets.TOKEN_FOR_API }}
  check-deployment:
    runs-on: ubuntu-latest
    needs: checkout-and-deployment
    steps:
      - name: Check deployment status
        run: "echo ${{needs.checkout-and-deployment.outputs.status_url}}"


