on:
  push:
    branches:
        - main

jobs:
  build_pages:
    runs-on: ubuntu-latest
    name: A job to build pages
    steps:
      - name: test
        run: printenv
      - name: Log into registry
        shell: bash
        env:
            SUPER_SECRET: ${{ secrets.CONTAINER_BUILDER_TOKEN }}
        run: echo $SUPER_SECRET | docker login containers.pkg.github.com -u ${{github.actor}} --password-stdin
      - name: Checkout
        uses: actions/checkout@v2
      - name: build_and_push_artifacts
        uses: ./ # Uses an action in the root directory
        id: build_and_push_artifacts
      - name: echo_out_results
        run: echo "Build complete ${{steps.build_and_push_artifacts.outputs.artifact_name}}"
      - name: copy_artifacts
        run:  |
               ls
               echo $(readlink -f "${{steps.build_and_push_artifacts.outputs.artifact_name}}") 
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-artifact
          path: ${{steps.build_and_push_artifacts.outputs.artifact_name}}
          if-no-files-found: error
      

