name: pages build and deployment
on: push
jobs:
  checkout-and-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Build page with Jekyll
        uses: paper-spa/pages-jekyll@v4.0.0
      - name: archive build output
        run: tar --directory _site/ -c -v -f artifact.tar .
      - name: upload_artifact
        id: upload_artifact
        uses: paper-spa/upload-artifact@main
        with:
          name: artifact
          path: ${{ github.workspace }}/artifact.tar
          token: ${{ secrets.TOKEN_FOR_API }}
    outputs:
      status_url: "${{ steps.upload_artifact.outputs.status_url }}"
  check-deployment:
    runs-on: ubuntu-latest
    needs: checkout-and-deployment
    steps:
      - name: Check deployment status
        uses: paper-spa/check-deployment-status@main
        with:
          status_url: "${{ needs.checkout-and-deployment.outputs.status_url }}"
          token: ${{ secrets.TOKEN_FOR_API }}
