name: pages build and deployment
on: push
concurrency:
  group: main
  cancel-in-progress: true
jobs:
  test-artifact-ids:
    runs-on: ubuntu-latest
    steps:
      - name: test-artifact-ids
        run: echo "${{github.check_suite}}"
