on:
  push:
    branches:
        - main

jobs:
  build_pages:
    runs-on: ubuntu-latest
    name: A job to build pages
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: build_and_push_artifacts
        uses: ./ # Uses an action in the root directory
        id: build_and_push_artifacts
      - name: echo_out_results
        run: echo "Build complete ${{steps.build_and_push_artifacts.outputs.artifact_name}}"
      - name: copy_artifacts
        run: |
              
              export i=$(docker image ls | awk '{if (NR==2) print $3}')
              docker create image i -name "test"
              docker cp test:${{steps.build_and_push_artifacts.outputs.artifact_name}} .
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: ${{steps.build_and_push_artifacts.outputs.artifact_name}}"

      

