on:
  push:
    branches:
        - main

jobs:
  build_pages:
    runs-on: ubuntu-latest
    name: A job to build pages
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: build_and_push_artifacts
        uses: ./ # Uses an action in the root directory
        id: build_and_push_artifacts
      - name: echo_out_results
        run: echo "Build complete ${{steps.build_and_push_artifacts.outputs.artifact_name}}"
      - name: copy_artifacts
        run:  |
               ls
               echo $(readlink -f "${{steps.build_and_push_artifacts.outputs.artifact_name}}") 
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-artifact
          path: felipe-pages-build-test/${{steps.build_and_push_artifacts.outputs.artifact_name}}"

      

